-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\lab2\lab2_pkg.vhd
-- Created: 2015-08-19 00:49:37
-- 
-- Generated by MATLAB 8.4 and HDL Coder 3.5
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE lab2_pkg IS
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
END lab2_pkg;

